# Generated by Django 4.0.5 on 2022-06-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0002_alter_problem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='url',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
