# Generated by Django 4.0.5 on 2022-06-10 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0004_alter_problem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
