# Generated by Django 4.0.5 on 2022-07-13 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainAPP', '0005_alter_playground_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('password', models.TextField(blank=True, null=True)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('total_problems', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
                ('participates', models.ManyToManyField(related_name='participates', to=settings.AUTH_USER_MODEL)),
                ('problems', models.ManyToManyField(to='mainAPP.problem')),
            ],
        ),
    ]
