# Generated by Django 4.0.5 on 2022-07-18 18:40

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0006_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='mainAPP.challenge'),
        ),
    ]
